### ISSUE TITLE
Reminder to uncomment the cleanup before this becomes a patch

### ISSUE THREAD

**Issue by Drupal-Infrastructure** [grasmash/composer-scaffold#15]
Saw this and didnt want us to forget it.

https://github.com/grasmash/composer-scaffold/blob/master/tests/src/Functional/ScaffoldTest.php#L86-L87

**Comment by ryanaslett** [comment]
^ thats me.

**Comment by greg-1-anderson** [comment]
The provided link points to HEAD of master rather than a specific sha, but I think this refers to the tearDown method, which has been uncommented.

**Comment by greg-1-anderson** [comment]
The teardown calls are all uncommented in the latest HEAD of master.
