### ISSUE TITLE
Determine which types of events to react to

### ISSUE THREAD

**Issue by ryanaslett** [grasmash/composer-scaffold#17]
Composer plugins can react to both ScriptEvents and PackageEvents. 

The other composer scaffold is reacting to both PackageEvents and ScriptEvents: https://github.com/drupal-composer/drupal-scaffold/blob/master/src/Plugin.php#L52-L55.

I think the ScriptEvent is the right one for us since we pretty much want all of the metadata from all installed packages so that we can calculate the cascade of overrides (i.e. wouldnt want to scaffold after each package as it is installed)

But given that, I think we need to also react to POST_CREATE_PROJECT_CMD as well as POST_INSTALL_CMD. 

Tests to prove that composer install, composer create-project, composer require package-with-scaffoldstuff, etc would be goods.

**Comment by greg-1-anderson** [comment]
Before we determine which events we need to react to, can we specify the desired behavior? The last sentence above nearly does it, except it contains "etc".

- After `composer install`, the scaffold operation should run and place all files.
- After `composer update`, the scaffold operation should run and place all files. If a scaffold file was removed from an updated package, it will not necessarily be removed from disk.
- After `composer require`, the scaffold operation should run and place all files. It is not necessary to isolate the scaffolding to only newly-added projects as long as any allowed and added project has its scaffold files placed.
- No action is taken after `composer remove`. Scaffolded files that are no longer part of the project remain on disk.

Did I miss anything vis-a-vis the requirements on when the scaffolding operation should run?

**Comment by greg-1-anderson** [comment]
So, I ran into an issue here. In the process of writing tests for the various ways we hook into Composer, I was considering the `require` use case.

- For good DX, we would like `require org/project` to scaffold any files provided by that project
- For good security/reliability, we only want to scaffold files from allowed projects in composer.json

These two goals are a little bit at odds when adding new projects, as the new project is probably not allowed in the composer.json file.

In an ideal situation, how would we like this to work? At the moment, in the tests I am pre-adding a package to the "allowed list", and then using `compose require` to add that same package to the fixture's dependencies. In this way I can confirm that `composer require` scaffolds the new files. In order for this to work, though, I had to make it NOT be an error to allow a project that is not yet in the `require` or `require-dev` section of the composer.json file.

I'm not sure if we can detect which command we are being called from, and perhaps prompt (if possible) to ask the user whether the project should be added to the "allowed" list. If this does work, it might be a good solution.

**Comment by greg-1-anderson** [comment]
Prior to getting our post-update-event, we could ask for a post-install-package event. This is called after `composer require`, but it is also called one for every package during `composer install`. Maybe by using both a pre-install-package event and a post-install-package event we might be able to tell the difference between `install` and `require`.

**Comment by greg-1-anderson** [comment]
I believe #19 now resolves this. I changed the handling of allowed packages to make it not be an error if a package is allowed but not required. We can go back to making this an error if desired (to better detect typos in the allowed section, for example).

**Comment by ryanaslett** [comment]
I think the only thing outstanding here is ensuring it works with `composer create-project` which will mostly likely be its primary use case, and the followup todo to have it warn a user if they require something that wants to scaffold files but cant because it's not yet allowed to.

**Comment by greg-1-anderson** [comment]
Note that the first item was resolved in #29, and the second is being tracked in #30.
