### ISSUE TITLE
Remove operation

### ISSUE THREAD

**Issue by greg-1-anderson** [grasmash/composer-scaffold#21]
User story:

> As a maintainer of a project that provides scaffold files,
> I would like to have a mechanism for removing files that were formerly scaffolded
> so that users are not confused by obsolete files left behind in their projects

Example:
```
"[web-root]/obsolete.php": {
    "mode": "remove",
    "path": "path/to/optional/obsolete.php"
}
```
The `path` is optional. If present, the specified file will be copied to the destination path, but only if there is a file already at that location. If there is no file at the destination, then the scaffold file will not be copied.  If there is no `path` element, then any file at the destination will be deleted.

Scaffold files that need to be removed could be replaced by a file that says something to the effect of "This file is no longer needed. You may delete it."

If a user wanted to keep an obsolete file in their repository, then they can override the scaffold operation as usual:
```
"[web-root]/obsolete.php": false
```

**Comment by ryanaslett** [comment]
> If a user wanted to keep an obsolete file in their repository, then they can override the scaffold operation as usual:

I think that the users wouldn't know they needed to keep the file until it disappeared as a result of an upstream change. Then again I think this use case is rare enough that there probably wont be an automated way to manage conflicting control between project maintainers and site owners. If a project maintainer has a file they want to move or maybe merge with another file, and the site maintainer has changes to that file they do not want overridden, then Im not sure how we could handle that conflict without overbearing complexity.

**Comment by grasmash** [comment]
> The path is optional. If present, the specified file will be copied to the destination path, but only if there is a file already at that location. If there is no file at the destination, then the scaffold file will not be copied. If there is no path element, then any file at the destination will be deleted.

I have to say, this is confusing. I would suggest this behavior:

1. If a package maintainer adds a file mapping with mode `remove` ... 
  a. AND the site owner has allowed that package to manage that file (e.g., mode is replace), the file should be removed.
  b. AND the site owner has NOT allowed that package to manage that file (e.g., mode is skip), nothing should happen to the file. A warning should be output for verbose output.

**Comment by greg-1-anderson** [comment]
1.a: If the package maintainer has added a file mapping with mode `remove`, then the mode will be remove, not replace.

Perhaps we should just close this issue as "not needed at this time", though?

**Comment by greg-1-anderson** [comment]
I am starting to think that perhaps the functionality originally conceived here could instead be provided by #28.

Closing as a duplicate.
