### ISSUE TITLE
Consider making web-root location optional

### ISSUE THREAD

**Issue by phenaproxima** [grasmash/composer-scaffold#24]
I think this location only makes sense to web-based projects like Drupal core. Granted, this plugin is being written for inclusion in Drupal core, so that's not wrong; but for more generic uses, I don't think we'd necessarily want to enforce the inclusion of the web-root location.

**Comment by greg-1-anderson** [comment]
Perhaps we could rename `web-root` to simply `root`. It could default to either `web` or `.` if not specified.

I strongly believe there should be some identifier, be it `[web-root]`, `[root]` or something else that project assets should include at the head of their path, as opposed to allowing the use of simple paths like `./index.php` that are implicitly relative to some unnamed location. I am flexible about what that name should be, or whether it should have a default value.

I sort of prefer being strict here, though; if a project does not declare its web root, that should be a scaffolding error.  Also, I think scaffolding is only useful for web-based projects -- at least, I cannot off the top of my head think why you would want to convolve project file locations other than to place files in specific locations to placate the web server. I suppose there may be other use cases, though.

**Comment by phenaproxima** [comment]
I concur with this idea. Let us rename `[web-root]` to `[root]`, and require it to be declared in the top-level composer.json.

**Comment by greg-1-anderson** [comment]
On the Mac I was able to transform these pretty easily via:
```
f -exec sed -i '' -e 's/web-root/root/g' {} \;
```
Something similar should be done for the `getWebRoot` method. I'm going to hold off on this for a bit to avoid creating conflicts with other open PRs, and to give time for others to comment on the name if desired.

**Comment by grasmash** [comment]
Renaming web-root to root may confuse people who think of root as the git/repo root. We _are_ talking about a web root and this is a Drupal specific plugin. We decided to add Drupalisms to this plugin, so I'm not sure if there's a lot of value in considering non-Drupal use cases. What are they?

**Comment by greg-1-anderson** [comment]
I think that this plugin is useful for any web-based, composer-managed project, and `web-root` could be applicable to non-Drupal as well as Drupal sites. I cannot think of a non-webserver-based use-case for this plugin, though.

**Comment by paul-m** [comment]
`web-root` is better as long as we document what it does. I'd call it `docroot` but it's fine either way. It could be optional (or really, default to `.`) because that's one of our use cases: We want to place scaffold files in our root directory for the 'tarball' legacy template.

**Comment by greg-1-anderson** [comment]
At the [composer in core initiative meeting](https://drupal.slack.com/archives/C392CHBEW/p1557940017075200), we decided to leave the default behavior in place.
